export type PaymentsOrderType = {
    beneficiaryName: string|null
    beneficiaryEmail: string|null
    claimCode: string|null
}

export type OrderWithAutoGeneratedId = PaymentsOrderType & {
    id: string
}
