import { ValueObject } from 'domains/core/entity/value-object';
import type { OrderWithAutoGeneratedId } from 'domains/entities/payments.order/type';

class PaymentsOrderValueObject extends ValueObject<OrderWithAutoGeneratedId> {
    static factory(order: OrderWithAutoGeneratedId) {
        return new PaymentsOrderValueObject(order);
    }
}


export { PaymentsOrderValueObject };
